---
- project:
    check:
      jobs:
        - ansible-tox-integration:
            voting: false

- job:
    name: ansible-tox-integration
    parent: tox
    vars:
      tox_envlist: integration
    voting: false
    nodeset: centos-8-1vcpu
